min_supported_versions:
  gpu_compute_requirement: "70"
  docker_requirement: "19.03"
  conda_requirement: "22.11"

cudf_requirements:
  cuda_requirement: "11.2"
  driver_requirement: "450.80.02"
  compute_requirement: "7.0"

symbols: 
  CHECK_SYMBOL: "ğŸš¨"
  OK_MARK: "âœ…"
  X_MARK: "âŒ"
  DOCTOR_SYMBOL: "ğŸ§‘â€âš•ï¸"