name: rapid-env
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2024.8.30=hf0a4a13_0
  - libffi=3.4.2=h3422bc3_5
  - libsqlite=3.46.1=hc14010f_0
  - libzlib=1.3.1=hfb2fe0b_1
  - ncurses=6.5=h7bae524_1
  - openssl=3.3.2=h8359307_0
  - pip=24.2=pyh8b19718_1
  - python=3.10.15=h7d35d02_0_cpython
  - readline=8.2=h92ec313_1
  - setuptools=74.1.2=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tzdata=2024a=h8827d51_1
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - pip:
      - click==8.1.7
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - nvidia-ml-py3==7.352.0
      - psutil==6.0.0
      - pygments==2.18.0
      - pynvml==11.5.3
      - rich==13.8.1
      - PyYAML==6.0.2
      - yml==0.0.1
prefix: /opt/miniconda3/envs/rapid-env
variables:
  gpu_compute_requirement: "70"
  docker_requirement: "19.03"
  conda_requirement: "22.11"
