name: rapids-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # Use a specific Python version
  - pip
  - setuptools
  - wheel
  - openssl
  - ca-certificates
  - libffi
  - ncurses
  - readline
  - tk
  - xz
  - pip:
      - click==8.1.7
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - nvidia-ml-py3==7.352.0
      - psutil==6.0.0
      - pygments==2.18.0
      - pynvml==11.5.3
      - rich==13.8.1
      - PyYAML==6.0.2
      - yml==0.0.1
      - pytest==8.3.3
      - cuda-python
